use std::collections::{HashMap, HashSet};

lazy_static! {
    pub static ref IGNORED_SECTIONS: HashMap<&'static str, HashSet<&'static str>> = hashmap! {
        "Definition and Usage" => hashset! {
            "<html>", "<head>", "<title>", "<body>", "<h1>", "<h2>", "<h3>",
            "<h4>", "<h5>", "<h6>", "<p>", "<br>", "<hr>", "<abbr>", "<address>",
            "<b>", "<bdi>", "<bdo>", "<blockquote>", "<cite>", "<code>", "<del>",
            "<dfn>", "<em>", "<i>", "<ins>", "<kbd>", "<mark>", "<meter>", "<pre>",
            "<progress>", "<q>", "<rp>", "<rt>", "<ruby>", "<s>", "<samp>", "<small>",
            "<strong>", "<sub>", "<sup>", "<template>", "<time>", "<u>", "<var>", "<wbr>",
            "<form>", "<input>", "<textarea>", "<button>", "<select>", "<optgroup>",
            "<option>", "<label>", "<fieldset>", "<legend>", "<datalist>", "<output>",
            "<iframe>", "<img>", "<map>", "<area>", "<canvas>", "<figcaption>", "<figure>",
            "<picture>", "<svg>", "<audio>", "<source>", "<track>", "<video>", "<a>",
            "<link>", "<nav>", "<ul>", "<ol>", "<li>", "<dl>", "<dt>", "<dd>", "<table>",
            "<caption>", "<th>", "<tr>", "<td>", "<thead>", "<tbody>", "<tfoot>", "<col>",
            "<colgroup>", "<style>", "<div>", "<span>", "<header>", "<footer>", "<main>",
            "<section>", "<article>", "<aside>", "<details>", "<dialog>", "<summary>",
            "<data>", "<head>", "<meta>", "<base>", "<script>", "<noscript>", "<embed>",
            "<object>", "<param>",
        },
        "Exercises and Quizzes" => hashset! {
            "<html>", "<head>", "<title>", "<body>", "<h1>", "<h2>", "<h3>",
            "<h4>", "<h5>", "<h6>", "<p>", "<br>", "<hr>", "<abbr>", "<address>",
            "<b>", "<bdi>", "<bdo>", "<blockquote>", "<cite>", "<code>", "<del>",
            "<dfn>", "<em>", "<i>", "<ins>", "<kbd>", "<mark>", "<meter>", "<pre>",
            "<progress>", "<q>", "<rp>", "<rt>", "<ruby>", "<s>", "<samp>", "<small>",
            "<strong>", "<sub>", "<sup>", "<template>", "<time>", "<u>", "<var>", "<wbr>",
            "<form>", "<input>", "<textarea>", "<button>", "<select>", "<optgroup>",
            "<option>", "<label>", "<fieldset>", "<legend>", "<datalist>", "<output>",
            "<iframe>", "<img>", "<map>", "<area>", "<canvas>", "<figcaption>", "<figure>",
            "<picture>", "<svg>", "<audio>", "<source>", "<track>", "<video>", "<a>",
            "<link>", "<nav>", "<ul>", "<ol>", "<li>", "<dl>", "<dt>", "<dd>", "<table>",
            "<caption>", "<th>", "<tr>", "<td>", "<thead>", "<tbody>", "<tfoot>", "<col>",
            "<colgroup>", "<style>", "<div>", "<span>", "<header>", "<footer>", "<main>",
            "<section>", "<article>", "<aside>", "<details>", "<dialog>", "<summary>",
            "<data>", "<head>", "<meta>", "<base>", "<script>", "<noscript>", "<embed>",
            "<object>", "<param>",
        },
        "HTML Reference" => hashset! {
            "<html>", "<head>", "<title>", "<body>", "<h1>", "<h2>", "<h3>",
            "<h4>", "<h5>", "<h6>", "<p>", "<br>", "<hr>", "<abbr>", "<address>",
            "<b>", "<bdi>", "<bdo>", "<blockquote>", "<cite>", "<code>", "<del>",
            "<dfn>", "<em>", "<i>", "<ins>", "<kbd>", "<mark>", "<meter>", "<pre>",
            "<progress>", "<q>", "<rp>", "<rt>", "<ruby>", "<s>", "<samp>", "<small>",
            "<strong>", "<sub>", "<sup>", "<template>", "<time>", "<u>", "<var>", "<wbr>",
            "<form>", "<input>", "<textarea>", "<button>", "<select>", "<optgroup>",
            "<option>", "<label>", "<fieldset>", "<legend>", "<datalist>", "<output>",
            "<iframe>", "<img>", "<map>", "<area>", "<canvas>", "<figcaption>", "<figure>",
            "<picture>", "<svg>", "<audio>", "<source>", "<track>", "<video>", "<a>",
            "<link>", "<nav>", "<ul>", "<ol>", "<li>", "<dl>", "<dt>", "<dd>", "<table>",
            "<caption>", "<th>", "<tr>", "<td>", "<thead>", "<tbody>", "<tfoot>", "<col>",
            "<colgroup>", "<style>", "<div>", "<span>", "<header>", "<footer>", "<main>",
            "<section>", "<article>", "<aside>", "<details>", "<dialog>", "<summary>",
            "<data>", "<head>", "<meta>", "<base>", "<script>", "<noscript>", "<embed>",
            "<object>", "<param>",
        },
        "HTML Tags" => hashset! {
            "<html>", "<head>", "<title>", "<body>", "<h1>", "<h2>", "<h3>",
            "<h4>", "<h5>", "<h6>", "<p>", "<br>", "<hr>", "<abbr>", "<address>",
            "<b>", "<bdi>", "<bdo>", "<blockquote>", "<cite>", "<code>", "<del>",
            "<dfn>", "<em>", "<i>", "<ins>", "<kbd>", "<mark>", "<meter>", "<pre>",
            "<progress>", "<q>", "<rp>", "<rt>", "<ruby>", "<s>", "<samp>", "<small>",
            "<strong>", "<sub>", "<sup>", "<template>", "<time>", "<u>", "<var>", "<wbr>",
            "<form>", "<input>", "<textarea>", "<button>", "<select>", "<optgroup>",
            "<option>", "<label>", "<fieldset>", "<legend>", "<datalist>", "<output>",
            "<iframe>", "<img>", "<map>", "<area>", "<canvas>", "<figcaption>", "<figure>",
            "<picture>", "<svg>", "<audio>", "<source>", "<track>", "<video>", "<a>",
            "<link>", "<nav>", "<ul>", "<ol>", "<li>", "<dl>", "<dt>", "<dd>", "<table>",
            "<caption>", "<th>", "<tr>", "<td>", "<thead>", "<tbody>", "<tfoot>", "<col>",
            "<colgroup>", "<style>", "<div>", "<span>", "<header>", "<footer>", "<main>",
            "<section>", "<article>", "<aside>", "<details>", "<dialog>", "<summary>",
            "<data>", "<head>", "<meta>", "<base>", "<script>", "<noscript>", "<embed>",
            "<object>", "<param>",
        },
        "References" => hashset! {
            "<html>", "<head>", "<title>", "<body>", "<h1>", "<h2>", "<h3>",
            "<h4>", "<h5>", "<h6>", "<p>", "<br>", "<hr>", "<abbr>", "<address>",
            "<b>", "<bdi>", "<bdo>", "<blockquote>", "<cite>", "<code>", "<del>",
            "<dfn>", "<em>", "<i>", "<ins>", "<kbd>", "<mark>", "<meter>", "<pre>",
            "<progress>", "<q>", "<rp>", "<rt>", "<ruby>", "<s>", "<samp>", "<small>",
            "<strong>", "<sub>", "<sup>", "<template>", "<time>", "<u>", "<var>", "<wbr>",
            "<form>", "<input>", "<textarea>", "<button>", "<select>", "<optgroup>",
            "<option>", "<label>", "<fieldset>", "<legend>", "<datalist>", "<output>",
            "<iframe>", "<img>", "<map>", "<area>", "<canvas>", "<figcaption>", "<figure>",
            "<picture>", "<svg>", "<audio>", "<source>", "<track>", "<video>", "<a>",
            "<link>", "<nav>", "<ul>", "<ol>", "<li>", "<dl>", "<dt>", "<dd>", "<table>",
            "<caption>", "<th>", "<tr>", "<td>", "<thead>", "<tbody>", "<tfoot>", "<col>",
            "<colgroup>", "<style>", "<div>", "<span>", "<header>", "<footer>", "<main>",
            "<section>", "<article>", "<aside>", "<details>", "<dialog>", "<summary>",
            "<data>", "<head>", "<meta>", "<base>", "<script>", "<noscript>", "<embed>",
            "<object>", "<param>",
        },
        "Report Error" => hashset! {
            "<html>", "<head>", "<title>", "<body>", "<h1>", "<h2>", "<h3>",
            "<h4>", "<h5>", "<h6>", "<p>", "<br>", "<hr>", "<abbr>", "<address>",
            "<b>", "<bdi>", "<bdo>", "<blockquote>", "<cite>", "<code>", "<del>",
            "<dfn>", "<em>", "<i>", "<ins>", "<kbd>", "<mark>", "<meter>", "<pre>",
            "<progress>", "<q>", "<rp>", "<rt>", "<ruby>", "<s>", "<samp>", "<small>",
            "<strong>", "<sub>", "<sup>", "<template>", "<time>", "<u>", "<var>", "<wbr>",
            "<form>", "<input>", "<textarea>", "<button>", "<select>", "<optgroup>",
            "<option>", "<label>", "<fieldset>", "<legend>", "<datalist>", "<output>",
            "<iframe>", "<img>", "<map>", "<area>", "<canvas>", "<figcaption>", "<figure>",
            "<picture>", "<svg>", "<audio>", "<source>", "<track>", "<video>", "<a>",
            "<link>", "<nav>", "<ul>", "<ol>", "<li>", "<dl>", "<dt>", "<dd>", "<table>",
            "<caption>", "<th>", "<tr>", "<td>", "<thead>", "<tbody>", "<tfoot>", "<col>",
            "<colgroup>", "<style>", "<div>", "<span>", "<header>", "<footer>", "<main>",
            "<section>", "<article>", "<aside>", "<details>", "<dialog>", "<summary>",
            "<data>", "<head>", "<meta>", "<base>", "<script>", "<noscript>", "<embed>",
            "<object>", "<param>",
        },
        "Thank You For Helping Us!" => hashset! {
            "<html>", "<head>", "<title>", "<body>", "<h1>", "<h2>", "<h3>",
            "<h4>", "<h5>", "<h6>", "<p>", "<br>", "<hr>", "<abbr>", "<address>",
            "<b>", "<bdi>", "<bdo>", "<blockquote>", "<cite>", "<code>", "<del>",
            "<dfn>", "<em>", "<i>", "<ins>", "<kbd>", "<mark>", "<meter>", "<pre>",
            "<progress>", "<q>", "<rp>", "<rt>", "<ruby>", "<s>", "<samp>", "<small>",
            "<strong>", "<sub>", "<sup>", "<template>", "<time>", "<u>", "<var>", "<wbr>",
            "<form>", "<input>", "<textarea>", "<button>", "<select>", "<optgroup>",
            "<option>", "<label>", "<fieldset>", "<legend>", "<datalist>", "<output>",
            "<iframe>", "<img>", "<map>", "<area>", "<canvas>", "<figcaption>", "<figure>",
            "<picture>", "<svg>", "<audio>", "<source>", "<track>", "<video>", "<a>",
            "<link>", "<nav>", "<ul>", "<ol>", "<li>", "<dl>", "<dt>", "<dd>", "<table>",
            "<caption>", "<th>", "<tr>", "<td>", "<thead>", "<tbody>", "<tfoot>", "<col>",
            "<colgroup>", "<style>", "<div>", "<span>", "<header>", "<footer>", "<main>",
            "<section>", "<article>", "<aside>", "<details>", "<dialog>", "<summary>",
            "<data>", "<head>", "<meta>", "<base>", "<script>", "<noscript>", "<embed>",
            "<object>", "<param>",
        },
        "Tutorials" => hashset! {
            "<html>", "<head>", "<title>", "<body>", "<h1>", "<h2>", "<h3>",
            "<h4>", "<h5>", "<h6>", "<p>", "<br>", "<hr>", "<abbr>", "<address>",
            "<b>", "<bdi>", "<bdo>", "<blockquote>", "<cite>", "<code>", "<del>",
            "<dfn>", "<em>", "<i>", "<ins>", "<kbd>", "<mark>", "<meter>", "<pre>",
            "<progress>", "<q>", "<rp>", "<rt>", "<ruby>", "<s>", "<samp>", "<small>",
            "<strong>", "<sub>", "<sup>", "<template>", "<time>", "<u>", "<var>", "<wbr>",
            "<form>", "<input>", "<textarea>", "<button>", "<select>", "<optgroup>",
            "<option>", "<label>", "<fieldset>", "<legend>", "<datalist>", "<output>",
            "<iframe>", "<img>", "<map>", "<area>", "<canvas>", "<figcaption>", "<figure>",
            "<picture>", "<svg>", "<audio>", "<source>", "<track>", "<video>", "<a>",
            "<link>", "<nav>", "<ul>", "<ol>", "<li>", "<dl>", "<dt>", "<dd>", "<table>",
            "<caption>", "<th>", "<tr>", "<td>", "<thead>", "<tbody>", "<tfoot>", "<col>",
            "<colgroup>", "<style>", "<div>", "<span>", "<header>", "<footer>", "<main>",
            "<section>", "<article>", "<aside>", "<details>", "<dialog>", "<summary>",
            "<data>", "<head>", "<meta>", "<base>", "<script>", "<noscript>", "<embed>",
            "<object>", "<param>",
        },
        "Default CSS Settings" => hashset! {
            "<html>", "<head>", "<title>", "<body>", "<h1>", "<h2>", "<h3>",
            "<h4>", "<h5>", "<h6>", "<p>", "<br>", "<hr>", "<abbr>", "<address>",
            "<b>", "<bdo>", "<blockquote>", "<cite>", "<code>", "<del>", "<dfn>",
            "<em>", "<i>", "<ins>", "<kbd>", "<mark>", "<meter>", "<pre>", "<progress>",
            "<q>", "<rp>", "<rt>", "<s>", "<samp>", "<small>", "<strong>", "<sub>",
            "<sup>", "<time>", "<u>", "<var>", "<form>", "<input>", "<textarea>",
            "<button>", "<select>", "<optgroup>", "<option>", "<label>", "<fieldset>",
            "<legend>", "<datalist>", "<output>", "<iframe>", "<img>", "<map>", "<area>",
            "<canvas>", "<figcaption>", "<figure>", "<audio>", "<source>", "<track>",
            "<video>", "<a>", "<link>", "<nav>", "<ul>", "<ol>", "<li>", "<dl>", "<dt>",
            "<dd>", "<table>", "<caption>", "<th>", "<tr>", "<td>", "<thead>",
            "<tbody>", "<tfoot>", "<col>", "<colgroup>", "<style>", "<div>", "<span>",
            "<header>", "<footer>", "<section>", "<article>", "<aside>", "<details>",
            "<summary>", "<head>", "<meta>", "<base>", "<script>", "<noscript>", "<embed>",
            "<object>", "<param>",
        },
        "Related Pages" => hashset! {
            "<html>", "<head>", "<title>", "<body>", "<h1>", "<h2>", "<h3>",
            "<h4>", "<h5>", "<h6>", "<p>", "<br>", "<hr>", "<abbr>", "<address>",
            "<b>", "<bdo>", "<blockquote>", "<cite>", "<code>", "<del>", "<dfn>",
            "<em>", "<i>", "<ins>", "<kbd>", "<mark>", "<meter>", "<pre>", "<progress>",
            "<q>", "<s>", "<samp>", "<small>", "<strong>", "<sub>", "<sup>", "<time>",
            "<u>", "<var>", "<form>", "<input>", "<textarea>", "<button>", "<select>",
            "<optgroup>", "<option>", "<label>", "<fieldset>", "<legend>", "<datalist>",
            "<output>", "<iframe>", "<img>", "<map>", "<area>", "<figcaption>", "<figure>",
            "<picture>", "<svg>", "<audio>", "<source>", "<track>", "<video>", "<a>",
            "<link>", "<nav>", "<ul>", "<ol>", "<li>", "<dl>", "<dt>", "<dd>", "<table>",
            "<caption>", "<th>", "<tr>", "<td>", "<col>", "<colgroup>", "<style>", "<div>",
            "<span>", "<header>", "<footer>", "<section>", "<article>", "<aside>",
            "<details>", "<dialog>", "<summary>", "<head>", "<meta>", "<base>", "<script>",
            "<noscript>", "<embed>", "<object>", "<param>",
        },
        "More Examples" => hashset! {
            "<head>", "<body>", "<h1>", "<h2>", "<h3>", "<h4>", "<h5>",
            "<h6>", "<p>", "<br>", "<hr>", "<abbr>", "<b>", "<blockquote>", "<code>",
            "<del>", "<ins>", "<kbd>", "<pre>", "<q>", "<small>", "<template>",
            "<u>", "<form>", "<textarea>", "<button>", "<select>", "<option>",
            "<fieldset>", "<legend>", "<iframe>", "<img>", "<map>", "<area>", "<canvas>",
            "<figcaption>", "<figure>", "<svg>", "<source>", "<a>", "<ul>", "<ol>", "<li>",
            "<table>", "<caption>", "<th>", "<tr>", "<td>", "<thead>", "<tbody>",
            "<tfoot>", "<col>", "<colgroup>", "<style>", "<header>", "<footer>", "<main>",
            "<article>", "<aside>", "<details>", "<summary>", "<head>", "<meta>",
        },
        "Tips and Notes" => hashset! {
            "<br>", "<b>", "<blockquote>", "<del>", "<progress>", "<input>",
            "<label>", "<fieldset>", "<canvas>", "<audio>", "<video>", "<a>", "<style>",
            "<footer>", "<script>",
        },
        "Differences Between HTML and XHTML" => hashset! {
            "<script>",
        },
        "Plug-ins" => hashset! {
            "<object>",
        },
        "Setting the Viewport" => hashset! {
            "<meta>",
        },
        "Suggestion" => hashset! {
            "<embed>",
        },
        "Warning" => hashset! {
            "<embed>",
        },
    };
}
