[package]
name = "web-reference-factory"
version = "0.1.0"
edition = "2021"
description = "Factory for generating reference of HTML Tag Specifications"
license = "MIT or Apache-2.0"
include = ["pacakges/web-reference-factory/src/**/*", "Cargo.toml", "LICENSE-MIT", "readme.md"]
homepage = "https://github.com/Nejat/web-reference"
repository = "https://github.com/Nejat/web-reference"
authors = ["Nejat<nejatoz@gmail.com>"]
readme = "readme.md"
keywords = ["html", "reference"]
categories = ["Web programming"]

[dependencies]
anyhow = { version = "1" }
indexmap = { version = "1", features = ["serde"] }
itertools = { version = "0.10" }
lazy-regex = { version = "2" }
lazy_static = { version = "1" }
maplit = { version = "1" }
parking_lot = { version = "0.12" }
reqwest = { version = "0.11", features = ["blocking"] }
select = { version = "0.5" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["indexmap"] }
thiserror = { version = "1" }
web-reference = { path = "../../../web-reference", features = ["serialize", "ordered-map"] }

[features]
build = []
analyze = []